//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelliStock_WebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTUAL_SUMMARY
    {
        public string MARKET_STATUS { get; set; }
        public Nullable<double> MARKET_VOLUME { get; set; }
        public Nullable<double> MARKET_VALUE { get; set; }
        public Nullable<double> MARKET_TRADES { get; set; }
        public Nullable<double> SYMBOLS_ADVANCED { get; set; }
        public Nullable<double> SYMBOLS_DECLINED { get; set; }
        public Nullable<double> SYMBOLS_UNCHANGED { get; set; }
        public Nullable<double> SYMBOLS_TOTAL { get; set; }
        public Nullable<double> KSE100_CURRENT { get; set; }
        public Nullable<double> KSE100_HIGH { get; set; }
        public Nullable<double> KSE100_LOW { get; set; }
        public Nullable<double> KSE100_CHANGE { get; set; }
        public Nullable<double> ALLSHARE_CURRENT { get; set; }
        public Nullable<double> ALLSHARE_HIGH { get; set; }
        public Nullable<double> ALLSHARE_LOW { get; set; }
        public Nullable<double> ALLSHARE_CHANGE { get; set; }
        public Nullable<double> KSE30_CURRENT { get; set; }
        public Nullable<double> KSE30_HIGH { get; set; }
        public Nullable<double> KSE30_LOW { get; set; }
        public Nullable<double> KSE30_CHANGE { get; set; }
        public Nullable<double> KMI30_CURRENT { get; set; }
        public Nullable<double> KMI30_HIGH { get; set; }
        public Nullable<double> KMI30_LOW { get; set; }
        public Nullable<double> KMI30_CHANGE { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public int ID { get; set; }
    }
}
