//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelliStock_WebService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KSE_DATABASEEntities : DbContext
    {
        public KSE_DATABASEEntities()
            : base("name=KSE_DATABASEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ACTUAL_SUMMARY> ACTUAL_SUMMARY { get; set; }
        public DbSet<SUMMARY> SUMMARies { get; set; }
        public DbSet<SYSTEM_PREDICTION> SYSTEM_PREDICTION { get; set; }
        public DbSet<USER_PREDICTION> USER_PREDICTION { get; set; }
        public DbSet<USER_STATUS> USER_STATUS { get; set; }
        public DbSet<USER> USERS { get; set; }
    }
}
