//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelliStock_WebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUMMARY
    {
        public int SYMBOL_ID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string SYMBOL_NAME { get; set; }
        public string SYMBOL_CATEGORY { get; set; }
        public Nullable<double> SYMBOL_LDCP { get; set; }
        public Nullable<double> SYMBOL_OPEN { get; set; }
        public Nullable<double> SYMBOL_HIGH { get; set; }
        public Nullable<double> SYMBOL_LOW { get; set; }
        public Nullable<double> SYMBOL_CURRENT { get; set; }
        public Nullable<double> SYMBOL_CHANGE { get; set; }
        public Nullable<double> SYMBOL_VOLUME { get; set; }
    }
}
