//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelliStock_WebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public USER()
        {
            this.USER_PREDICTION = new HashSet<USER_PREDICTION>();
            this.USER_STATUS = new HashSet<USER_STATUS>();
        }
    
        public int Id { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string USER_NAME { get; set; }
        public string EMAIL { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string GENDER { get; set; }
        public string MOBILE { get; set; }
        public string CITY { get; set; }
    
        public virtual ICollection<USER_PREDICTION> USER_PREDICTION { get; set; }
        public virtual ICollection<USER_STATUS> USER_STATUS { get; set; }
    }
}
